import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireAuth, isAdminRole, AuthenticationError } from '@/lib/auth'
import * as XLSX from 'xlsx'

// GET /api/campaigns/export-all - Export all campaigns as Excel
export async function GET(request: NextRequest) {
  try {
    const user = await requireAuth(request)

    const where: Record<string, unknown> = { isDeleted: false }
    if (!isAdminRole(user.role)) {
      where.createdById = user.id
    }

    const campaigns = await prisma.campaign.findMany({
      where,
      include: {
        createdBy: {
          select: { id: true, name: true, email: true },
        },
        campaignType: {
          select: { id: true, name: true, color: true, icon: true },
        },
        _count: {
          select: { seekers: true },
        },
      },
      orderBy: { createdAt: 'desc' },
    })

    // ── Overview sheet ──────────────────────────────────────────────────────
    const overviewRows = campaigns.map((c) => ({
      'Campaign Name': c.name,
      Type: c.type,
      Status: c.status,
      'Target Audience': c.targetAudience,
      'Start Date': new Date(c.startDate).toLocaleDateString(),
      'End Date': c.endDate ? new Date(c.endDate).toLocaleDateString() : 'Ongoing',
      'Budget ($)': c.budget ?? '',
      Reach: c.reach ?? '',
      'Total Seekers': c._count.seekers,
      Description: c.description ?? '',
      'Created By': c.createdBy?.name ?? '',
      'Created At': new Date(c.createdAt).toLocaleDateString(),
    }))

    // ── Analytics sheet ─────────────────────────────────────────────────────
    const analyticsRows = campaigns.map((c) => ({
      'Campaign Name': c.name,
      Type: c.type,
      Status: c.status,
      Views: c.views ?? 0,
      'Net Follows': c.netFollows ?? 0,
      'Total Watch Time (s)': c.totalWatchTime ?? 0,
      'Avg Watch Time (s)': c.averageWatchTime ?? 0,
      'Total Interactions': c.totalInteractions ?? 0,
      Reactions: c.reactions ?? 0,
      Comments: c.comments ?? 0,
      Shares: c.shares ?? 0,
      Saves: c.saves ?? 0,
      'Link Clicks': c.linkClicks ?? 0,
      'Engagement Rate (%)':
        c.views && c.views > 0
          ? Number(((c.totalInteractions ?? 0) / c.views * 100).toFixed(2))
          : 0,
    }))

    const wb = XLSX.utils.book_new()

    const wsOverview = XLSX.utils.json_to_sheet(overviewRows)
    XLSX.utils.book_append_sheet(wb, wsOverview, 'Campaigns Overview')

    const wsAnalytics = XLSX.utils.json_to_sheet(analyticsRows)
    XLSX.utils.book_append_sheet(wb, wsAnalytics, 'Analytics')

    // ── Summary sheet ────────────────────────────────────────────────────────
    const activeCampaigns = campaigns.filter((c) => c.status === 'ACTIVE').length
    const totalReach = campaigns.reduce((sum, c) => sum + (c.reach ?? 0), 0)
    const totalSeekers = campaigns.reduce((sum, c) => sum + c._count.seekers, 0)
    const totalBudget = campaigns.reduce((sum, c) => sum + (c.budget ?? 0), 0)

    const summaryRows = [
      { Metric: 'Total Campaigns', Value: campaigns.length },
      { Metric: 'Active Campaigns', Value: activeCampaigns },
      { Metric: 'Total Reach', Value: totalReach },
      { Metric: 'Total Seekers', Value: totalSeekers },
      { Metric: 'Total Budget ($)', Value: Number(totalBudget.toFixed(2)) },
      {
        Metric: 'Overall Conversion Rate (%)',
        Value:
          totalReach > 0
            ? Number(((totalSeekers / totalReach) * 100).toFixed(2))
            : 0,
      },
      {
        Metric: 'Report Generated',
        Value: new Date().toLocaleString(),
      },
      { Metric: 'Generated By', Value: user.name },
    ]

    const wsSummary = XLSX.utils.json_to_sheet(summaryRows)
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary')

    const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })

    const filename = `all-campaigns-report-${new Date().toISOString().split('T')[0]}.xlsx`

    return new NextResponse(buffer, {
      headers: {
        'Content-Type':
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    if (error instanceof AuthenticationError) {
      return NextResponse.json({ error: error.message }, { status: 401 })
    }
    console.error('Error exporting campaigns:', error)
    return NextResponse.json(
      { error: 'Failed to export campaigns' },
      { status: 500 }
    )
  }
}
